### ISSUE TITLE
Can I gzip my site?

### ISSUE THREAD

**Issue by filipburman** [mollie/OpenCart#21]
Didn't know where to write or ask this question. But when I launched my site in September 2014 it didn't work to gzip the site. I haven't updated the mollie module since then and I thought I would do that now. And at the same time see, is it possible to gzip the site now?

**Comment by lvgunst** [comment]
First our module didn't work because the module relied heavily on javascript. Since the change in version 6 this changed. If you update the OpenCart module to version 6+ you should be able to use GZIP compression.

Please check the [release page](https://github.com/mollie/OpenCart/releases) for the latest version.
