### ISSUE TITLE
v.9.2.8 & OC 2.3.0.2 => not working!

### ISSUE THREAD

**Issue by osworx** [mollie/OpenCart#211]
As subject states, using these 2 versions.

Short summary of the instalaltion and operation afterwards:

1. Extension is not installable via the embedded installer (OC.2.3.x and 3.x)
Files have to be extracted locally and moved by FTP into the installation.
What for does OC have an Installer?

2. The biggest issue (!!) - checkout does not work
Enabled e.g. Credicard (w. Testkey) and all what I can see is the Mollie Logo (extern !!!) and the Continue button.
Where is the summary of the order??

3. Using German as Language > does not work!
Everything is still in English >> not useable this way for manay (and not allowed to mix languages).

Btw: I am the creator of the German Language Translation for OpenCart.
**As developer you should know, that wether OC 2.x nor OC 3.x a language like german does exist!
And in OC 2.x the Language name is de-DE.**
And your German translation included in this version is also not really useable.
Why did you not asked someone who speaks German?

4. Installing this extension (see # 1 above) and I see several Payment Methods in the backend!
**But NONE of them are displayed as Active**.

Has this be done this way (every and each payment as extra module ??) ?!
Because opening one of them is "opening all" at once.

5. Extension wants to be "backward compatible" and has several old files from former OC versions (< 2.2.0.x) as well as latetest (.twig) in one (1) package!
And what is this extension doing because of that?
Including these old files like include(__DIR__."/../../../german/payment/mollie.php");

6. Backend- and Frontend header files are called every time (not only when they are required!

7. OC 2.x is calling these includes by:
`<file name="catalog/view/theme/*/template/common/header.tpl" error="skip">
        <operation>
            <search position="after"><![CDATA[<head>]]></search>
            <add><![CDATA[<?php echo comercia\util::html()->variables();?>]]>
            </add>
        </operation>
    </file>
`

while OC 3.x is doing it that way:
`<file name="catalog/view/theme/*/template/common/header.twig" error="skip">
        <operation >
            <search position="after"><![CDATA[<head>]]></search>
            <add><![CDATA[{{ html_variables() }}]]>
            </add>
        </operation>
    </file>`

Sorry, but do you really think this is the best way (calling functions directly inside template files) ??

8. Changing system files (e.g. like **system/library/template/twig.php** or **system/engine/action.php** ) is also not the best reputation.

Sorry, that all seems to be a it 'harsh'.
Because this is a "free" extension.

No. Is it not,
Does no matter if free or paid, if you publish such a work, it should work.
**Currently: this Molli version is NOT compatible with OPenCart 2.3.0.2.**

Do you have plans to publish a working version?

**Comment by QualityWorks** [comment]
Hello,

We have multiple sites running with this extension on 1.5.6.4 upto 3.0.3.2
They are all working.
The installer (not the GitHub package) is also working for all versions of
OC that has the installer.
Obviously, we would not release it if it didn't work.
As for the backwards compatibility, as well as the multiple files, opening
a single page. There are multiple technical reasons why we are doing it
this way.
The alternative, of having a seperate settings page per payment method
seems very user unfriendly. (For example the Pay.nl module)

I'm more than happy to discuss this module with you. Your very suggestive
email about the nonfunction of the module does rattle me a bit, if you have
questions about choices we made, you can ask them, instead of assuming we
made mistakes.

For our example shops, please see here:

http://mollie-1564.qwdev.nl (this one is currently not working as we are
working on version 9.3.0 and we are fixing a bug)
http://mollie-2031.qwdev.nl
http://mollie-2302.qwdev.nl
http://mollie-3020.qwdev.nl
http://mollie-3202.qwdev.nl

Obviously, if the module wouldn't be working for 2.3.0.2, we would have a
lot of complaints.

Best regards,

Taco

Quality Works.

Op di 5 mei 2020 17:28 schreef OSWorX <notifications@github.com>:
