### ISSUE TITLE
Uw betaling is niet voltooid. Betaling is echter wel doorgekomen.

### ISSUE THREAD

**Issue by tc662** [mollie/OpenCart#43]
Als een klant een bestelling plaatst krijgt hij/zij na de betaling het venster Uw betaling is niet voltooid. De betaling is mislukt. De betaling is echter wel binnengekomen.

**Comment by ndijkstra** [comment]
Hallo! Zou je je partner ID kunnen doorgeven? Dan kan ik even voor je kijken.

**Comment by tc662** [comment]
Hoi Nick,

Het partner id is 607147



On Fri, Jul 15, 2016 at 3:19 PM, Nick Dijkstra < notifications@github.com [notifications@github.com] > wrote:
Hallo! Zou je je partner ID kunnen doorgeven? Dan kan ik even voor je kijken.

**Comment by LarsSnoek** [comment]
Wij hebben het taal bestand noodzakelijk aangepast zodat ze eigenlijk nog steeds de pagina in beeld krijgen dat de betaling mislukt is maar doordat we die tekst hebben aangepast met de informatie dat het gelukt is gaan ze in ieder geval niet meer dubbel betalen!!
Ik vind het een slechte zaak dat men dit nog steeds niet opgelost heeft, het heeft me handen vol geld gekost met crediteren van dubbele betalingen!

**Comment by mollierobbert** [comment]
To summarize in English: you're experiencing customers paying for the same order twice due to an e-mail being sent early in the order process with a non-paid status.

Sadly, there's not much we can do about this. We're following OpenCart's default order flow. We agree the flow can be confusing, but we do not have the resources to start hacking into the default OpenCart flow.

Please try upgrading to OpenCart 2.3, where the issue has likely already been resolved. Or, hire a developer to hack around the default OpenCart flow.

Again, please note this is a flaw in OpenCart's order flow, not in Mollie's OpenCart module.
