### ISSUE TITLE
OC 2.1.0.1

### ISSUE THREAD

**Issue by LarsSnoek** [mollie/OpenCart#50]
Hoi

Wij gebruiken nu sinds een jaar Opencart, we gebruiken versie 2.1.0.1 met daarbij een template en vele modules, nu is het zo dat bij de laatste versie van de Mollie module voor OC 2.1 de 6.30 module deze niet goed werkt met AQC, daarvan gebruiken wij versie 6.3.3!
Het inmiddels bekende euvel dat men na de correcte betaling de melding krijgt dat de betaling niet gelukt is!
Nu werd ons ongeveer 4 maanden geleden verteld dat er een nieuwe versie in de maak is en jawel die is er nu, maar niet voor de iets oudere versie van OC!
Gaat deze nog wel komen want volledig overstappen op OC 2.3 is voor ons geen optie omdat wij veel custom aanpassingen hebben aan onze shop, graag een reactie!

**Comment by mollierobbert** [comment]
Hi Lars, we've indeed recently released a separate module for OpenCart 2.3.

The issue you're experiencing with OpenCart 2.1 is due to a fault in the default payment flow of that OpenCart version. We don't have the resources to start hacking into the default OC 2.1 flow, so I'm sorry to say we can't help you with this.

Perhaps the developers who've customized your 2.1 setup can fix this issue as well for you by changing the email template's contents.

Otherwise, we can't do much for you except advise you to upgrade to OpenCart 2.3. Sorry for the inconvenience.
